apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-test
  namespace: default
  labels:
    app: java-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-test
  template:
    metadata:
      labels:
        app: java-test
    spec: 
      terminationGracePeriodSeconds: 1
      containers:
      - name: docker-container
        image: 513704694763.dkr.ecr.us-west-2.amazonaws.com/docker-container:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9090